# Generated by Django 5.2.6 on 2025-09-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_alter_mission_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
