# Generated by Django 5.2.6 on 2025-09-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='bread',
            new_name='breed',
        ),
    ]
