# Generated by Django 5.2.6 on 2025-09-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_rename_bread_cat_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
